version: '3.8'

services:
  adminer:
    container_name: adminer-prod-codenaute
    image: adminer
    ports:
      - 8080:8080
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=postgres

  server:
    container_name: server-prod-codenaute
    build:
      context: ./server
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_PROD_PORT=${DB_PROD_PORT}
      - DB_PROD_HOST=${DB_PROD_HOST}
      - DB_PROD_USER=${DB_PROD_USER}
      - DB_PROD_PASSWORD=${DB_PROD_PASSWORD}
      - DB_PROD_DATABASE=${DB_PROD_DATABASE}
      - GRAPHQL_PORT=${GRAPHQL_PORT}
    restart: always
    expose:
      - 5000
    depends_on:
      - adminer

  client:
    container_name: client-prod-codenaute
    build:
      context: ./client
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    restart: always
    expose:
      - 3000

  gateway:
    image: nginx
    ports:
      - ${GATEWAY_PORT}:80
    depends_on:
      - server
      - client
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    restart: always

networks:
  default:
    driver: bridge

volumes:
  database-prod:
