version: '3.8'

services:
  postgres:
    container_name: postgres-codenaute
    image: postgres:14.6-alpine
    restart: always
    env_file:
      - ./database/.env.database
    expose:
      - 5432
    volumes:
      - database-prod:/var/lib/postgresql/data

  postgres-test:
    container_name: db-test-codenaute
    image: postgres:14.6-alpine
    restart: always
    env_file:
      - ./database/.env.test
    expose:
      - 2345
    volumes:
      - database-test:/var/lib/postgresql/data
    command: -p 2345

  redis:
    container_name: redis-codenaute
    image: redis:alpine
    expose:
      - 6379

  adminer:
    container_name: adminer-codenaute
    image: adminer
    ports:
      - 8080:8080
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=postgres

  server:
    container_name: server-codenaute
    build:
      context: ./server
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    env_file:
      - ./server/.env.server
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - redis
      - adminer
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    container_name: client-codenaute
    build:
      context: ./client
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    env_file:
      - ./client/.env.client
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules

  gateway:
    image: nginx
    ports:
      - ${GATEWAY_PORT}:80
    depends_on:
      - server
      - client
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    restart: always

networks:
  default:
    driver: bridge

volumes:
  database-prod:
  database-test:
