version: '3.8'

services:
  postgres:
    container_name: postgres-coder
    image: postgres:14.6-alpine
    command: --skip-grant-tables
    env_file:
      - ./database/.env.database
    restart: always
    networks:
      - compose-bridge
    expose:
      - 5432
    volumes:
      - ./database/postgres:/docker-entrypoint-initdb.d

  adminer:
    container_name: adminer-coder
    image: adminer
    ports:
      - 8080:8080
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    networks:
      - compose-bridge

  redis:
    container_name: redis-coder
    image: redis:alpine
    expose:
      - 6379
    networks:
      - compose-bridge

  server:
    container_name: server-coder
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env.server
    restart: always
    networks:
      - compose-bridge
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules

networks:
  compose-bridge:
    driver: bridge
