/*This file was generated by NativeWind. Do not edit!*/
const { NativeWindStyleSheet: _NativeWindStyleSheet } = require('nativewind');
_NativeWindStyleSheet.create({
	styles: {
		'*': {
			borderTopWidth: 0,
			borderRightWidth: 0,
			borderBottomWidth: 0,
			borderLeftWidth: 0,
			borderStyle: 'solid',
			borderTopColor: '#e5e7eb',
			borderRightColor: '#e5e7eb',
			borderBottomColor: '#e5e7eb',
			borderLeftColor: '#e5e7eb'
		},
		'': {
			borderTopWidth: 0,
			borderRightWidth: 0,
			borderBottomWidth: 0,
			borderLeftWidth: 0,
			borderStyle: 'solid',
			borderTopColor: '#e5e7eb',
			borderRightColor: '#e5e7eb',
			borderBottomColor: '#e5e7eb',
			borderLeftColor: '#e5e7eb'
		},
		html: {
			lineHeight: 1.5,
			fontFamily: 'ui-sans-serif'
		},
		body: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		hr: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		'abbr:where([title])': {
			textDecorationLine: 'underline',
			textDecorationColor: 'black',
			textDecorationStyle: 'dotted'
		},
		code: {
			fontFamily: 'ui-monospace',
			fontSize: '1em'
		},
		kbd: {
			fontFamily: 'ui-monospace',
			fontSize: '1em'
		},
		samp: {
			fontFamily: 'ui-monospace',
			fontSize: '1em'
		},
		pre: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		small: {
			fontSize: '80%'
		},
		sub: {
			fontSize: '75%',
			lineHeight: 0,
			position: 'relative'
		},
		sup: {
			fontSize: '75%',
			lineHeight: 0,
			position: 'relative'
		},
		button: {
			backgroundColor: 'transparent'
		},
		input: {
			opacity: 1,
			color: '#9ca3af'
		},
		optgroup: {
			fontFamily: 'inherit',
			fontSize: '100%',
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0,
			paddingTop: 0,
			paddingRight: 0,
			paddingBottom: 0,
			paddingLeft: 0
		},
		select: {
			textTransform: 'none'
		},
		textarea: {
			opacity: 1,
			color: '#9ca3af'
		},
		"[type='button']": {
			backgroundColor: 'transparent'
		},
		"[type='reset']": {
			backgroundColor: 'transparent'
		},
		"[type='submit']": {
			backgroundColor: 'transparent'
		},
		':-moz-ui-invalid': {
			shadowOffset: {
				width: 0,
				height: 0
			},
			shadowRadius: 0,
			shadowColor: 'black',
			shadowOpacity: 1
		},
		blockquote: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		dl: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		dd: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		h1: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		h2: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		h3: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		h4: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		h5: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		h6: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		figure: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		p: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		fieldset: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0,
			paddingTop: 0,
			paddingRight: 0,
			paddingBottom: 0,
			paddingLeft: 0
		},
		legend: {
			paddingTop: 0,
			paddingRight: 0,
			paddingBottom: 0,
			paddingLeft: 0
		},
		ol: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0,
			paddingTop: 0,
			paddingRight: 0,
			paddingBottom: 0,
			paddingLeft: 0
		},
		ul: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0,
			paddingTop: 0,
			paddingRight: 0,
			paddingBottom: 0,
			paddingLeft: 0
		},
		menu: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0,
			paddingTop: 0,
			paddingRight: 0,
			paddingBottom: 0,
			paddingLeft: 0
		},
		img: {
			maxWidth: '100%'
		},
		video: {
			maxWidth: '100%'
		},
		'[hidden]': {
			display: 'none'
		},
		'!container': {
			width: '100%'
		},
		container: {
			width: '100%'
		},
		'!container@0': {
			maxWidth: 640
		},
		'container@0': {
			maxWidth: 640
		},
		'!container@1': {
			maxWidth: 768
		},
		'container@1': {
			maxWidth: 768
		},
		'!container@2': {
			maxWidth: 1024
		},
		'container@2': {
			maxWidth: 1024
		},
		'!container@3': {
			maxWidth: 1280
		},
		'container@3': {
			maxWidth: 1280
		},
		'!container@4': {
			maxWidth: 1536
		},
		'container@4': {
			maxWidth: 1536
		},
		'!shadow@0': {
			elevation: 3,
			shadowColor: 'rgba(0, 0, 0, 0.1)'
		},
		'shadow@0': {
			elevation: 3,
			shadowColor: 'rgba(0, 0, 0, 0.1)'
		},
		'!shadow@1': {
			shadowOffset: {
				width: 0,
				height: 2
			},
			shadowRadius: 6,
			shadowColor: 'rgba(0, 0, 0, 0.1)',
			shadowOpacity: 1
		},
		'shadow@1': {
			shadowOffset: {
				width: 0,
				height: 2
			},
			shadowRadius: 6,
			shadowColor: 'rgba(0, 0, 0, 0.1)',
			shadowOpacity: 1
		},
		'!shadow@2': {
			shadowOffset: {
				width: 0,
				height: 2
			},
			shadowRadius: 6,
			shadowColor: 'rgba(0, 0, 0, 0.1)',
			shadowOpacity: 1
		},
		'shadow@2': {
			shadowOffset: {
				width: 0,
				height: 2
			},
			shadowRadius: 6,
			shadowColor: 'rgba(0, 0, 0, 0.1)',
			shadowOpacity: 1
		},
		'sr-only': {
			position: 'absolute',
			width: 1,
			height: 1,
			paddingTop: 0,
			paddingRight: 0,
			paddingBottom: 0,
			paddingLeft: 0,
			marginTop: -1,
			marginRight: -1,
			marginBottom: -1,
			marginLeft: -1,
			overflow: 'hidden',
			borderTopWidth: 0,
			borderRightWidth: 0,
			borderBottomWidth: 0,
			borderLeftWidth: 0
		},
		'not-sr-only': {
			paddingTop: 0,
			paddingRight: 0,
			paddingBottom: 0,
			paddingLeft: 0,
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0,
			overflow: 'visible'
		},
		absolute: {
			position: 'absolute'
		},
		relative: {
			position: 'relative'
		},
		'm-1': {
			marginTop: 4,
			marginRight: 4,
			marginBottom: 4,
			marginLeft: 4
		},
		'm-4': {
			marginTop: 16,
			marginRight: 16,
			marginBottom: 16,
			marginLeft: 16
		},
		'mt-2': {
			marginTop: 8
		},
		'line-clamp-none': {
			overflow: 'visible'
		},
		flex: {
			display: 'flex'
		},
		'!hidden': {
			display: 'none'
		},
		hidden: {
			display: 'none'
		},
		'h-1': {
			height: 4
		},
		'h-2': {
			height: 8
		},
		'h-4': {
			height: 16
		},
		'h-6': {
			height: 24
		},
		'h-8': {
			height: 32
		},
		'h-9': {
			height: 36
		},
		'w-1': {
			width: 4
		},
		'w-2': {
			width: 8
		},
		'flex-shrink': {
			flexShrink: 1
		},
		shrink: {
			flexShrink: 1
		},
		'flex-grow': {
			flexGrow: 1
		},
		grow: {
			flexGrow: 1
		},
		'flex-row': {
			flexDirection: 'row'
		},
		'flex-row-reverse': {
			flexDirection: 'row-reverse'
		},
		'flex-col': {
			flexDirection: 'column'
		},
		'flex-col-reverse': {
			flexDirection: 'column-reverse'
		},
		'flex-wrap': {
			flexWrap: 'wrap'
		},
		'flex-wrap-reverse': {
			flexWrap: 'wrap-reverse'
		},
		'flex-nowrap': {
			flexWrap: 'nowrap'
		},
		'place-content-center': {
			alignContent: 'center',
			justifyContent: 'stretch'
		},
		'place-content-between': {
			alignContent: 'space-between',
			justifyContent: 'stretch'
		},
		'place-content-around': {
			alignContent: 'space-around',
			justifyContent: 'stretch'
		},
		'place-content-stretch': {
			alignContent: 'stretch',
			justifyContent: 'stretch'
		},
		'content-center': {
			alignContent: 'center'
		},
		'content-start': {
			alignContent: 'flex-start'
		},
		'content-end': {
			alignContent: 'flex-end'
		},
		'content-between': {
			alignContent: 'space-between'
		},
		'content-around': {
			alignContent: 'space-around'
		},
		'content-stretch': {
			alignContent: 'stretch'
		},
		'items-start': {
			alignItems: 'flex-start'
		},
		'items-end': {
			alignItems: 'flex-end'
		},
		'items-center': {
			alignItems: 'center'
		},
		'items-baseline': {
			alignItems: 'baseline'
		},
		'items-stretch': {
			alignItems: 'stretch'
		},
		'justify-normal': {
			justifyContent: 'normal'
		},
		'justify-start': {
			justifyContent: 'flex-start'
		},
		'justify-end': {
			justifyContent: 'flex-end'
		},
		'justify-center': {
			justifyContent: 'center'
		},
		'justify-between': {
			justifyContent: 'space-between'
		},
		'justify-around': {
			justifyContent: 'space-around'
		},
		'justify-evenly': {
			justifyContent: 'space-evenly'
		},
		'justify-stretch': {
			justifyContent: 'stretch'
		},
		'self-auto': {
			alignSelf: 'auto'
		},
		'self-start': {
			alignSelf: 'flex-start'
		},
		'self-end': {
			alignSelf: 'flex-end'
		},
		'self-center': {
			alignSelf: 'center'
		},
		'self-stretch': {
			alignSelf: 'stretch'
		},
		'self-baseline': {
			alignSelf: 'baseline'
		},
		'overflow-hidden': {
			overflow: 'hidden'
		},
		'overflow-visible': {
			overflow: 'visible'
		},
		'overflow-scroll': {
			overflow: 'scroll'
		},
		truncate: {
			overflow: 'hidden'
		},
		rounded: {
			borderTopLeftRadius: 4,
			borderTopRightRadius: 4,
			borderBottomRightRadius: 4,
			borderBottomLeftRadius: 4
		},
		'rounded-b': {
			borderBottomRightRadius: 4,
			borderBottomLeftRadius: 4
		},
		'rounded-l': {
			borderTopLeftRadius: 4,
			borderBottomLeftRadius: 4
		},
		'rounded-r': {
			borderTopRightRadius: 4,
			borderBottomRightRadius: 4
		},
		'rounded-t': {
			borderTopLeftRadius: 4,
			borderTopRightRadius: 4
		},
		'rounded-bl': {
			borderBottomLeftRadius: 4
		},
		'rounded-br': {
			borderBottomRightRadius: 4
		},
		'rounded-tl': {
			borderTopLeftRadius: 4
		},
		'rounded-tr': {
			borderTopRightRadius: 4
		},
		border: {
			borderTopWidth: 1,
			borderRightWidth: 1,
			borderBottomWidth: 1,
			borderLeftWidth: 1
		},
		'border-x': {
			borderLeftWidth: 1,
			borderRightWidth: 1
		},
		'border-y': {
			borderTopWidth: 1,
			borderBottomWidth: 1
		},
		'border-b': {
			borderBottomWidth: 1
		},
		'border-l': {
			borderLeftWidth: 1
		},
		'border-r': {
			borderRightWidth: 1
		},
		'border-t': {
			borderTopWidth: 1
		},
		'border-solid': {
			borderStyle: 'solid'
		},
		'border-dashed': {
			borderStyle: 'dashed'
		},
		'border-dotted': {
			borderStyle: 'dotted'
		},
		'0)]': {
			backgroundColor: 'rgb(255,0,0)'
		},
		'bg-primary': {
			backgroundColor: '#44A5FE'
		},
		'p-1': {
			paddingTop: 4,
			paddingRight: 4,
			paddingBottom: 4,
			paddingLeft: 4
		},
		'p-14': {
			paddingTop: 56,
			paddingRight: 56,
			paddingBottom: 56,
			paddingLeft: 56
		},
		'p-16': {
			paddingTop: 64,
			paddingRight: 64,
			paddingBottom: 64,
			paddingLeft: 64
		},
		'p-2': {
			paddingTop: 8,
			paddingRight: 8,
			paddingBottom: 8,
			paddingLeft: 8
		},
		'p-3': {
			paddingTop: 12,
			paddingRight: 12,
			paddingBottom: 12,
			paddingLeft: 12
		},
		'p-8': {
			paddingTop: 32,
			paddingRight: 32,
			paddingBottom: 32,
			paddingLeft: 32
		},
		'text-left': {
			textAlign: 'left'
		},
		'text-center': {
			textAlign: 'center'
		},
		'text-right': {
			textAlign: 'right'
		},
		'text-justify': {
			textAlign: 'justify'
		},
		'font-bold': {
			fontWeight: '700'
		},
		uppercase: {
			textTransform: 'uppercase'
		},
		lowercase: {
			textTransform: 'lowercase'
		},
		capitalize: {
			textTransform: 'capitalize'
		},
		'normal-case': {
			textTransform: 'none'
		},
		italic: {
			fontStyle: 'italic'
		},
		'not-italic': {
			fontStyle: 'normal'
		},
		'text-[#336699]/[.35]': {
			color: 'rgba(51, 102, 153, .35)'
		},
		'text-blue-500': {
			color: '#3b82f6'
		},
		'text-yellow-500': {
			color: '#eab308'
		},
		underline: {
			textDecorationLine: 'underline'
		},
		'line-through': {
			textDecorationLine: 'line-through'
		},
		'no-underline': {
			textDecorationLine: 'none'
		},
		'decoration-solid': {
			textDecorationStyle: 'solid'
		},
		'decoration-double': {
			textDecorationStyle: 'double'
		},
		'decoration-dotted': {
			textDecorationStyle: 'dotted'
		},
		'decoration-dashed': {
			textDecorationStyle: 'dashed'
		},
		'space-x-2.children@0': {
			marginLeft: 8
		},
		'divide-x.children@0': {
			borderLeftWidth: 1,
			borderRightWidth: 0
		},
		'divide-y.children@0': {
			borderBottomWidth: 0,
			borderTopWidth: 1
		},
		'divide-solid.children@0': {
			borderStyle: 'solid'
		},
		'divide-dashed.children@0': {
			borderStyle: 'dashed'
		},
		'divide-dotted.children@0': {
			borderStyle: 'dotted'
		},
		elevation: {
			elevation: 3
		},
		'sm:container@0': {
			width: '100%'
		},
		'sm:container@1': {
			maxWidth: 640
		},
		'sm:container@2': {
			maxWidth: 768
		},
		'sm:container@3': {
			maxWidth: 1024
		},
		'sm:container@4': {
			maxWidth: 1280
		},
		'sm:container@5': {
			maxWidth: 1536
		},
		'hover:font-bold': {
			fontWeight: '700'
		},
		'before:hover:text-center': {
			textAlign: 'center'
		},
		'hover:before:text-center': {
			textAlign: 'center'
		},
		'focus:hover:text-center': {
			textAlign: 'center'
		},
		'hover:focus:text-center': {
			textAlign: 'center'
		},
		'sm:underline@0': {
			textDecorationLine: 'underline'
		}
	},
	atRules: {
		'!container': [
			[['media', '(min-width: 640px)']],
			[['media', '(min-width: 768px)']],
			[['media', '(min-width: 1024px)']],
			[['media', '(min-width: 1280px)']],
			[['media', '(min-width: 1536px)']]
		],
		container: [
			[['media', '(min-width: 640px)']],
			[['media', '(min-width: 768px)']],
			[['media', '(min-width: 1024px)']],
			[['media', '(min-width: 1280px)']],
			[['media', '(min-width: 1536px)']]
		],
		'!shadow': [[['media', 'android']], [['media', 'ios']], [['media', 'web']]],
		shadow: [[['media', 'android']], [['media', 'ios']], [['media', 'web']]],
		'space-x-2.children': [[['selector', '(> *:not(:first-child))']]],
		'divide-x.children': [[['selector', '(> *:not(:first-child))']]],
		'divide-y.children': [[['selector', '(> *:not(:first-child))']]],
		'divide-solid.children': [[['selector', '(> *:not(:first-child))']]],
		'divide-dashed.children': [[['selector', '(> *:not(:first-child))']]],
		'divide-dotted.children': [[['selector', '(> *:not(:first-child))']]],
		'sm:container': [
			[['media', '(min-width: 640px)']],
			[
				['media', '(min-width: 640px)'],
				['media', '(min-width: 640px)']
			],
			[
				['media', '(min-width: 640px)'],
				['media', '(min-width: 768px)']
			],
			[
				['media', '(min-width: 640px)'],
				['media', '(min-width: 1024px)']
			],
			[
				['media', '(min-width: 640px)'],
				['media', '(min-width: 1280px)']
			],
			[
				['media', '(min-width: 640px)'],
				['media', '(min-width: 1536px)']
			]
		],
		'sm:underline': [[['media', '(min-width: 640px)']]]
	},
	masks: {
		'hover:font-bold': 256,
		'before:hover:text-center': 256,
		'hover:before:text-center': 256,
		'focus:hover:text-center': 768,
		'hover:focus:text-center': 768
	},
	topics: {
		'!container': ['width'],
		container: ['width'],
		'sm:container': ['width'],
		'sm:underline': ['width']
	},
	childClasses: {
		'space-x-2': ['space-x-2.children'],
		'divide-x': ['divide-x.children'],
		'divide-y': ['divide-y.children'],
		'divide-solid': ['divide-solid.children'],
		'divide-dashed': ['divide-dashed.children'],
		'divide-dotted': ['divide-dotted.children']
	}
});
