version: '3.8'

services:
  mysql:
    container_name: mysql-coder
    build:
      dockerfile: Dockerfile
    image: mysql:8.0.31
    privileged: true
    command: --skip-grant-tables
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    restart: always

  adminer:
    container_name: adminer-coder
    image: adminer
    ports:
      - 8080:8080
    restart: always
    environment:
      - ADMINER_DEFAULT_SERVER=mysql

  redis:
    container_name: redis-coder
    image: redis:alpine
    ports:
      - 6379:6379

networks:
  default:
    driver: bridge
