/*This file was generated by NativeWind. Do not edit!*/
const { NativeWindStyleSheet: _NativeWindStyleSheet } = require('nativewind');
_NativeWindStyleSheet.create({
	styles: {
		'*': {
			borderTopWidth: 0,
			borderRightWidth: 0,
			borderBottomWidth: 0,
			borderLeftWidth: 0,
			borderStyle: 'solid',
			borderTopColor: '#e5e7eb',
			borderRightColor: '#e5e7eb',
			borderBottomColor: '#e5e7eb',
			borderLeftColor: '#e5e7eb'
		},
		'': {
			borderTopWidth: 0,
			borderRightWidth: 0,
			borderBottomWidth: 0,
			borderLeftWidth: 0,
			borderStyle: 'solid',
			borderTopColor: '#e5e7eb',
			borderRightColor: '#e5e7eb',
			borderBottomColor: '#e5e7eb',
			borderLeftColor: '#e5e7eb'
		},
		html: {
			lineHeight: 1.5,
			fontFamily: 'ui-sans-serif'
		},
		body: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		hr: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		'abbr:where([title])': {
			textDecorationLine: 'underline',
			textDecorationColor: 'black',
			textDecorationStyle: 'dotted'
		},
		code: {
			fontFamily: 'ui-monospace',
			fontSize: '1em'
		},
		kbd: {
			fontFamily: 'ui-monospace',
			fontSize: '1em'
		},
		samp: {
			fontFamily: 'ui-monospace',
			fontSize: '1em'
		},
		pre: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		small: {
			fontSize: '80%'
		},
		sub: {
			fontSize: '75%',
			lineHeight: 0,
			position: 'relative'
		},
		sup: {
			fontSize: '75%',
			lineHeight: 0,
			position: 'relative'
		},
		button: {
			backgroundColor: 'transparent'
		},
		input: {
			opacity: 1,
			color: '#9ca3af'
		},
		optgroup: {
			fontFamily: 'inherit',
			fontSize: '100%',
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0,
			paddingTop: 0,
			paddingRight: 0,
			paddingBottom: 0,
			paddingLeft: 0
		},
		select: {
			textTransform: 'none'
		},
		textarea: {
			opacity: 1,
			color: '#9ca3af'
		},
		"[type='button']": {
			backgroundColor: 'transparent'
		},
		"[type='reset']": {
			backgroundColor: 'transparent'
		},
		"[type='submit']": {
			backgroundColor: 'transparent'
		},
		':-moz-ui-invalid': {
			shadowOffset: {
				width: 0,
				height: 0
			},
			shadowRadius: 0,
			shadowColor: 'black',
			shadowOpacity: 1
		},
		blockquote: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		dl: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		dd: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		h1: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		h2: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		h3: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		h4: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		h5: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		h6: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		figure: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		p: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0
		},
		fieldset: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0,
			paddingTop: 0,
			paddingRight: 0,
			paddingBottom: 0,
			paddingLeft: 0
		},
		legend: {
			paddingTop: 0,
			paddingRight: 0,
			paddingBottom: 0,
			paddingLeft: 0
		},
		ol: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0,
			paddingTop: 0,
			paddingRight: 0,
			paddingBottom: 0,
			paddingLeft: 0
		},
		ul: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0,
			paddingTop: 0,
			paddingRight: 0,
			paddingBottom: 0,
			paddingLeft: 0
		},
		menu: {
			marginTop: 0,
			marginRight: 0,
			marginBottom: 0,
			marginLeft: 0,
			paddingTop: 0,
			paddingRight: 0,
			paddingBottom: 0,
			paddingLeft: 0
		},
		img: {
			maxWidth: '100%'
		},
		video: {
			maxWidth: '100%'
		},
		'[hidden]': {
			display: 'none'
		},
		container: {
			width: '100%'
		},
		'container@0': {
			maxWidth: 640
		},
		'container@1': {
			maxWidth: 768
		},
		'container@2': {
			maxWidth: 1024
		},
		'container@3': {
			maxWidth: 1280
		},
		'container@4': {
			maxWidth: 1536
		},
		flex: {
			display: 'flex'
		},
		'text-yellow-500': {
			color: '#eab308'
		}
	},
	atRules: {
		container: [
			[['media', '(min-width: 640px)']],
			[['media', '(min-width: 768px)']],
			[['media', '(min-width: 1024px)']],
			[['media', '(min-width: 1280px)']],
			[['media', '(min-width: 1536px)']]
		]
	},
	topics: {
		container: ['width']
	}
});
