#!/usr/bin/env sh

local_branch="$(git rev-parse --abbrev-ref HEAD)"
valid_branch_regex="^(jk|rv|nc)/(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)/[a-z0-9._-]+$"
message="There is something wrong with your branch name. Branch names must follow this regex: $valid_branch_regex. Your commit will be rejected. You should rename your branch to a valid name and try again."

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

exit 0
