# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-and-push.yml'
      - 'client/**'
      - 'server/**'
      - 'database/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Client Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/codenaute-client:latest

      - name: Build and Push Server Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/codenaute-server:latest

      - name: Build and Push Database Dev Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./database/dev/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/codenaute-db-dev:latest

      - name: Build and Push Database Test Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./database/test/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/codenaute-db-test:latest
