# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Client CI

on:
  pull_request:
    path:
      - '.github/workflows/client.yml'
      - 'client/**'

env:
  SERVICE_NAME: 'client'
  NODEJS_VERSION: '16.17.1'
  PNPM_VERSION: '7.16.0'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/codenaute:client

  workflow:
    needs: build-and-push
    runs-on: ubuntu-latest

    container:
      image: 'reynandev/codenaute:client'
      env:
        NODE_ENV: test
      ports:
        - 3000:3000
      volumes:
        - ${{ github.workspace }}:/app

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: Install dependencies globaly
        run: pnpm install

      - name: Install dependencies on client
        run: pnpm install
        working-directory: ./${{ env.SERVICE_NAME }}

      - name: Restore Github Cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.OS }}-platform-client-${{ hashFiles('pnpm-lock.yaml', 'client/pnpm-lock.yaml') }}

      - name: Run Prettier
        run: npx prettier --check .
        working-directory: ./${{ env.SERVICE_NAME }}

      - name: Run Tests
        run: pnpm test
        working-directory: ./${{ env.SERVICE_NAME }}
