# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Client CI

on:
  pull_request:
    path:
      - '.github/workflows/client.yml'
      - 'client/**'

env:
  SERVICE_NAME: 'client'
  NODEJS_VERSION: '16.17.1'
  PNPM_VERSION: '7.16.0'

jobs:
  workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: Start Node.js ${{ env.NODEJS_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODEJS_VERSION }}

      - name: Start pnpm ${{ env.PNPM_VERSION }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Install Dependencies
        run: make install

      - name: Restore Github Cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.OS }}-platform-client-${{ hashFiles('pnpm-lock.yaml', 'client/pnpm-lock.yaml') }}

      - name: Run Prettier
        working-directory: ./${{ env.SERVICE_NAME }}
        run: make prettier

  application-and-tests:
    needs: workflow
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: 'reynandev/codenaute:client'
      DOCKER_DATABASE: 'postgres:14.6-alpine'
    container:
      image: ${{ env.DOCKER_IMAGE }}
      env:
        NODE_ENV: test
      ports:
        - 3000:3000
      volumes:
        - ${{ github.workspace }}:/app

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: Make Install
        run: make install

      - name: Run Tests
        run: make test
        working-directory: ./${{ env.SERVICE_NAME }}
