# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Server CI

on:
  pull_request:
    path:
      - '.github/workflows/server.yml'
      - 'server/**'

env:
  SERVICE_NAME: 'server'
  NODEJS_VERSION: '16.17.1'
  PNPM_VERSION: '7.16.0'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/codenaute:server

  workflow:
    needs: build-and-push
    runs-on: ubuntu-latest
    environment: tests
    if: github.event.pull_request.draft == false
    env:
      NODE_ENV: test

    container:
      image: 'reynandev/codenaute:server'
      env:
        NODE_ENV: test
      ports:
        - 5000:5000
      volumes:
        - ${{ github.workspace }}:/app

    services:
      postgres-test:
        image: 'postgres:14.6-alpine'
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 2345:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v3

      - name: Install dependencies globaly
        run: pnpm install

      - name: Install dependencies on server
        run: pnpm install
        working-directory: ./${{ env.SERVICE_NAME }}

      - name: Restore Github Cache
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.OS }}-platform-server-${{ hashFiles('pnpm-lock.yaml', '**/pnpm-lock.yaml') }}

      - name: Run Prettier
        run: npx prettier --check .
        working-directory: ./${{env.SERVICE_NAME}}

      - name: Run Tests
        run: pnpm test
        working-directory: ./${{env.SERVICE_NAME}}
